server:
  port: 9999

spring:
  application:
    name: micro-server-gateway
  could:
    config:
      enabled: false
  profiles:
    active: dev


---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://yqkj:yc@localhost:4000/eureka
    registry-fetch-interval-seconds: 10

---
spring:
  profiles: test
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://yqkj:yc@eureka:4000/eureka

---
spring:
  profiles: prd
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://yqkj:yc@eureka:4000/eureka
